name: cthru-calculator
channels: [conda-forge, nodefaults]
dependencies:
  - python=3.10
  - pandas=1.5.*
  - sympy=1.11.*
  - openpyxl=3.*
  - rdflib=6.*
  - pygraphviz=1.7
  - ipysankeywidget=0.5.*
  - jupyter-book=0.13.*
  - jupyterlab=3.*
  - matplotlib=3.*
  - bqplot=0.12.*
  - notebook=6.*
  - jupytext=1.14.*
  - pytest=6.2.*
  - voila=0.3.*
  - tqdm=4.*
  - pyarrow=16.*
  - pip=23.*
  - pip:
      - git+https://github.com/ricklupton/floweaver.git@38215850519d08cd791145cde3c1e8fa0cfe928b#egg=floweaver
      - sphinx_probs_rdf==0.4.3
      - https://github.com/ukfires/probs-runner/archive/e13f5510ff59236827900d3185f0bd32594f4554.zip
      - git+https://github.com/probs-lab/flowprog.git@8720b12087bf44dc784c00120b3a146460b14601#egg=flowprog
      - oxrdflib==0.3.*
      - lxml_html_clean==0.1.*
