---
execute:
  echo: false
---

# feedstock_emission_factor {#sec-feedstock-emission-factor}

```{python}
#| output: false
from plot_levers import tabulate_lever, describe_lever_levels
```

```{python}
describe_lever_levels("feedstock_emission_factor")
```

This lever controls the emissions factor for upstream production of the feedstocks that enter the model.

Emissions factors for natural gas, coal, gas oil, propane and butane were taken from @desnzdefra_ghgconversionfactors_2023 scope 3 emissions factors data.

Approximate emissions factors for naphtha and ethane supply were based on the study by @nanthachatchavankul_specific_2012 for ethylene production in Thailand, which was assumed to be the mean value between reported values by @bousted_ecoprofiles_2005 (assumed minimum) and @desnzdefra_ghgconversionfactors_2023 (assumed maximum).

<!-- Question: is this representative enough? The value above was the assumed mean given the limited data available. -->

Biomass crop feedstocks are from @yuttitham_carbon_2011 for sugarcane production in Thailand (assumed mean value between the reported values by @sanches_towards_2023 as the assumed minimum and @chandra_life_2018 as the assumed maximum), and @farag_carbon_2018 for corn production in Egypt (assumed mean between the reported values by @giusti_environmental_2023 as the assumed minimum and @zhang_carbon_2017 as the assumed maximum).  Crop residues are represented by @desnzdefra_ghgconversionfactors_2023 scope 3 emissions for generic straw/grass biomass.

## Parameter data

@tbl-natural-gas-requirements shows parameter values for natural gas utility requirements.

```{python}
#| label: tbl-feedstock_emission-factor
#| tbl-cap: "`feedstock_emission_factor` parameter data. Values in kgCO~2e~ per tonne product."
tabulate_lever("feedstock_emission_factor", floatfmt=".0f")
```
