---
execute:
  echo: false
---

# frac_of_biomass_feedstock

```{python}
#| output: false
from plot_levers import plot_lever, describe_lever_levels, param_units
```

```{python}
describe_lever_levels("frac_of_biomass_feedstock")
```

This lever controls the mix of biomass sources used when producing bioethanol and biosyngas.

Currently about two-thirds of bioethanol comes from starch-based biomass (maize) with the rest from sugar-based biomass (sugarcane) [doe_global_2022]. Accounting for the ethanol yield from each biomass feedstock gives a baseline share of 72% ethanol from maize, 28% from sugarcane.

Historical global production of sugar cane, maize, [paddy] rice, and wheat were obtained from @fao_faostat_2024, and the trendlines were used to project production of each crop from 2020 to 2050.  Using typical sugarcane bagasse to sugarcane ratio by @nikodinovicrunic_carbonrichwastes_2013, corn stover to maize ratio by @ruan_corn_2019, rice straw to paddy rice ratio by irri_value_2018, and wheat straw to wheat ratio by @song_quantitative_2013, corresponding production of these residues can also be estimated from 2020 to 2050.

The fraction of the biomass available for ethanol production is 26% of the total sugar cane production and 14% of the total maize production using the data from @grointelligence_howbigethanol_2019 and @usda_feedgrains_2023, respectively. Similar to the work of @meng_planet_2023, 20% of the total crop residues produced are assumed to be available for chemical production.

In future the balance of ethanol from edible sugars versus lignocellulosic biomass is expected to shift. @lash_charting_2022 projected the future contributions of these to total fuel from 2020 to 2050, which is assumed to also apply to ethanol for chemicals. Together, after adjusting for ethanol yields, these give the projected shares of biomass contributing to bioethanol.

Feedstock shares used for biosyngas are assumed to be the same as for the lignocellulosic biomass used for bioethanol.

## Parameter data

```{python}
#| layout-ncol: 2
plot_lever("frac_of_biomass_feedstock", param_descriptions={
    "k_ethyl_alcohol_biomass_feedstock_fraction__0": "CornStover",
    "k_ethyl_alcohol_biomass_feedstock_fraction__1": "Maize",
    "k_ethyl_alcohol_biomass_feedstock_fraction__2": "Sugarcane",
    "k_ethyl_alcohol_biomass_feedstock_fraction__3": "SugarcaneBagasse",
    "k_ethyl_alcohol_biomass_feedstock_fraction__4": "WheatStraw",
    "k_ethyl_alcohol_biomass_feedstock_fraction__5": "RiceStraw",
    "k_syngas_biomass_feedstock_fraction__0": "CornStover",
    "k_syngas_biomass_feedstock_fraction__1": "SugarcaneBagasse",
    "k_syngas_biomass_feedstock_fraction__2": "WheatStraw",
    "k_syngas_biomass_feedstock_fraction__3": "RiceStraw",
})
```
