---
execute:
  echo: false
---

# product_demand

```{python}
#| output: false
from plot_levers import plot_lever, describe_lever_levels
```

```{python}
describe_lever_levels("product_demand")
```

This lever describes demand for polymers and end-of-life flows, based on @gao_evaluating_2024 stock modelling.

This uses a Dynamic Material Flow Analysis approach based on the assumption that, for durable goods, the per-capita stock of material in use is the more fundamental driver of material demand and waste flows. In the BAU scenario, the historical regional per-capita stock in each sector is correlated with regional GDP per-capita, then forecast to increase as GDP per capita increases per the second Shared Socioeconomic Pathway [@crespocuaresma_income_2017]. Coupled with the forecasted population growth by the United Nations [@un_population_2022], the regional sectoral demand is calculated by adding the yearly change of stock and waste generation. 

The percentage demand reduction levels represent a range of conceivable levels of demand reduction, which might be achieved through different specific strategies.  The levels refer to the in-use per-capita stock being reduced compared to the current North American level (which in turn drives the material demand and waste flows). More details can be found in @gao_evaluating_2024.

Similarly, for short-lived products such as packaging, the forecasted per-capita input increases as the fitted historical trend and forecasted GDP and population growth in the BAU scenario. In demand reduction scenarios, the regional input flow per capita is assumed to be capped to certain percentages of the current North American level.


## Parameter data

The plots below show the value over time of each parameter affected by this lever.

```{python}
#| label: fig-product-demand-1
#| layout-ncol: 2
#| fig-cap: "`product_demand` parameter data (part 1)"
#| fig-subcap:
#|  - "Demand for Packaging"
#|  - "Demand for Transportation"
#|  - "Demand for BuildingsAndConstruction"
#|  - "Demand for ElectricalAndElectronic"
plot_lever("product_demand", subset=range(0, 4))
```

```{python}
#| label: fig-product-demand-2
#| layout-ncol: 2
#| fig-cap: "`product_demand` parameter data (part 2)"
#| fig-subcap:
#|  - "Demand for ConsumerAndInstitutional"
#|  - "Demand for IndustrialMachinery"
#|  - "Demand for Textile"
#|  - "Demand for Other"
plot_lever("product_demand", subset=range(4, 8))
```

```{python}
#| label: fig-product-demand-3
#| layout-ncol: 2
#| fig-cap: "`product_demand` parameter data (part 3)"
#| fig-subcap:
#|  - "EOL from Packaging"
#|  - "EOL from Transportation"
#|  - "EOL from BuildingsAndConstruction"
#|  - "EOL from ElectricalAndElectronic"
plot_lever("product_demand", subset=range(8, 12))
```

```{python}
#| label: fig-product-demand-4
#| layout-ncol: 2
#| fig-cap: "`product_demand` parameter data (part 4)"
#| fig-subcap:
#|  - "EOL from ConsumerAndInstitutional"
#|  - "EOL from IndustrialMachinery"
#|  - "EOL from Textile"
#|  - "EOL from Other"
plot_lever("product_demand", subset=range(12, 16))
```
