---
execute:
  echo: false
---

# recycling {#sec-recycling}

```{python}
#| output: false
from plot_levers import plot_recycling_rates, describe_lever_levels, param_units
```

```{python}
describe_lever_levels("recycling")
```

This lever controls recycling rates for each polymer at end-of-life.

Plastics are made of two types of polymers: thermoplastics and thermosets.

- Thermoplastics are made up of single long chains of molecules such as low density polyethylene (LDPE), linear low-density polyethylene (LLDPE), high-density polyethylene (HDPE), polypropylene (PP), polystyrene (PS), polyvinyl chloride (PVC), polyethylene terephthalate (PET), and fibre polyphthalamide (PPA). They can be melted and formed again to original state with little to no loss in properties [@wikipedia_thermoplastic_2024]. It makes sense to mechanically recycle them.

- Thermosets involve cross-linking such as polyurethane (PUR) and styrene-butadiene rubber (SBR) or synthetic rubbers. Other polymers were placed under this category for simplicity. Melting them tends to induce curing and can change their properties [@wikipedia_thermosetting_2024]. It does not make sense to mechanical recycle them. They can be downcycled by cutting them up and re-using them, which is not mechanical recycling in this sense as we want them back to their original form and purpose. Hence, chemical recycling that breaks them down to their feedstock and/or monomer makes more sense as these can be used to produce the original polymer back.

Chemical recycling covers both more targeted processes to return polymers to monomers, and broader pyrolysis processes.

## Possible recycling routes

First the possible recycling routes in different scenarios are set for 3 levels of ambition, as summarised in @tbl-routes.

  ---------------------------------------------------------------
  Polymer type            Current    Practical     Ambitious
  ----------------------- ---------- ------------- --------------
  LDPE                    M / _      M / _         M / C         
                                                                 
  HDPE                    M / _      M / _         M / C         

  LLDPE                   _ / _      M / _         M / C         

  PET                     M / _      M / C         M / C         
                                                                 
  PP                      M / _      M / _         M / C         
                                                                 
  PVC                     _ / _      M / _         M / C         
                                                                 
  PS                      _ / _      M / C         M / C         
                                                                 
  Fibre PPA               _ / _      _ / C         M / C         

  PUR                     _ / _      _ / C         _ / C         
                                                                 
  SBR                     _ / _      _ / _         _ / C         
                                                                 
  Other polymers          _ / _      _ / _         _ / C         
  ---------------------------------------------------------------
  
: Current, improved and ambitious options for recycling routes by polymer.  "M" indicates suitability for mechanical recycling, "C" for chemical recycling. {#tbl-routes}

### Current routes

Currently the possibilities for recycling polymers are as follows:

-   LDPE, HDPE, and PET are widely recycled [@oecd_improving_2018]. There is virtually no chemical recycling today [@vangeem_plastic_2023]: all current recycling is mechanical.

-   PP can be mechanically recycled, but only 1% of the world production is recycled. Majority of the discarded PP goes to landfills and oceans [@basham_how_2019]. There is also a misconception that waste PP from health sector cannot be recycled, hence, majority are incinerated without recovering the energy [@interweave_polypropylene_2019].

-   LLDPE can be mechanically and chemically recycled. Because it is often blended with other types of plastics that make its recycling challenging, consequently, its recycling rate is generally low [@arkema_how_2023]. This is also compounded with the dwindling demand for LLDPE and about 60% is for single-use applications, hence, investments on recycling LLDPE needs to be economically justified [@richardson_lldpe_2018].

-   Mechanical recycling is recommended for PVC, but this is not happening now as it is mistaken to have low thermal stability and to generate toxic degradation products, which are misconceptions as it can be widely recycled [@lewandowski_brief_2022].

-   PS can be mechanically and chemically recycled [@maharana_review_2017]. Despite being so, PS recycling is not done globally at present, because it is not economically feasible [@marquez_catalytic_2023] and it is logistically difficult [@waring_can_2018]. Hence, it makes more sense to produce virgin PS than recycle it.

-   PUR recycling is not predominantly done, despite the effort from manufacturers and legislators. Most PUR wastes end up in landfills [@kemona_polyurethane_2020].

-   With tire industry representing 65% of the global rubber production, most rubber wastes go to landfills [@fazli_waste_2020].

-   PPA is generally mixed with other plastics, hence, there is limited recycling, with most going to incineration and land filling [@hirschberg_recycling_2023].

### Future routes

Expectations for future improvements for each polymer are:

-   Following from the current practice: LDPE, HDPE, and PET will continue to be mechanically recycled [@oecd_improving_2018].

-   LLDPE, PP and PVC can be recycled more, via mechanical recycling [@oecd_improving_2018;@lewandowski_brief_2022].

-   PS and PET can be both mechanically and chemically recycled [@maharana_review_2017;@gao_evaluating_2024].

-   Mechanical recycling degrades the polymer properties of PUR [@rossingnolo_recycling_2024] and PPA [@hirschberg_recycling_2023], so chemical recycling is most appropriate.

This forms the "practical limit" level. 

Beyond this, all the rest of the polymers can be chemically recycled provided the technologies became technically, economically, and environmentally feasible.  This forms the "ambitious" level.

## Quantifying recycling rates

The baseline overall global recycling rate is 9% according to @oecd_globalplastics_2022.  This is distributed across the relevant polymers for each level [@tbl-routes] based on the mass flow quantities of each polymer in the baseline model.  The recycling rate for PP is 1% [@basham_how_2019], and equal recycling rates for HDPE, LDPE and PET of 30% was assumed to give an overall mass-weighted recycling rate of 9%.

The reference business-as-usual projection in recycling rate growth from @oecd_globalplastics_2022 reaches 16% by 2050.  We assume growth in mechanical recycling rates on the polymers already recycled to 15% and 35% respectively.  Additional growth in recycling is distributed across the other recycling routes added in this level of @tbl-routes at 15% for LLDPE and 5% for others.

The more ambitious scenario from @oecd_globalplastics_2022 reaches 47% overall recycling rate by 2050.  This increase is achieved by increasing recycling rates to 50% for all polymers which can be mechanically recycled in @tbl-routes, together with 15% chemical recycling of all polymers.

## Parameter data

The plots below show the change in recycling rates over time for each polymer affected by this lever.

```{python}
#| label: fig-recycling-1
#| fig-cap: "`recycling` parameter data (part 1)"
#| fig-subcap:
#|  - LDPEPolyethylene
#|  - HDPEPolyethylene
#|  - PPPolypropylene
#|  - PSPolystyrene
plot_recycling_rates(subset=range(0, 4))
```

```{python}
#| label: fig-recycling-2
#| fig-cap: "`recycling` parameter data (part 2)"
#| fig-subcap:
#|  - PVCPolyvinylChloride
#|  - PETPolyethyleneTerephthalatePolyesters
#|  - Polyurethane
#|  - SyntheticRubbers
plot_recycling_rates(subset=range(4, 8))
```

```{python}
#| label: fig-recycling-3
#| fig-cap: "`recycling` parameter data (part 3)"
#| fig-subcap:
#|  - OtherPolymers
#|  - LLDPE
#|  - FibrePPA
plot_recycling_rates(subset=range(8, 11)) #1
```
